# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/website',
                'doc_host': 'https://maimanuel.github.io',
                'git_url': 'https://github.com/maimanuel/website',
                'lib_path': 'website'},
  'syms': {}}